"""Formula tests against hand-verified figures.

Every input below is taken from Apple Inc.'s Form 10-K for the fiscal year ended
28 September 2024 (and the FY2023 comparatives printed in the same filing, which is what
the average-balance ratios need). Expected outputs were computed by hand from those
figures, so a regression in a formula — average equity quietly becoming ending equity,
say, or a sign flip on capex — fails the test rather than shifting a plausible-looking
number.

All statement figures are in millions of USD, matching the filing.
"""

from __future__ import annotations

import pytest

from src.analytics import ratios as r
from src.analytics import trends as t

# --- Apple Inc. FY2024 10-K -------------------------------------------------------
# Consolidated Statements of Operations
AAPL_FY2024 = {
    "revenue": 391_035.0,             # Total net sales
    "cogs": 210_352.0,                # Total cost of sales
    "gross_profit": 180_683.0,        # Gross margin
    "operating_income": 123_216.0,    # Operating income
    "pretax_income": 123_485.0,       # Income before provision for income taxes
    "tax_provision": 29_749.0,        # Provision for income taxes
    "net_income": 93_736.0,           # Net income
    "eps_diluted": 6.08,              # Diluted EPS
    "shares_diluted": 15_408.095,     # Diluted weighted-average shares (millions)
    # Consolidated Balance Sheets
    "cash": 29_943.0,                 # Cash and cash equivalents
    "receivables": 33_410.0,          # Accounts receivable, net
    "inventory": 7_286.0,             # Inventories
    "current_assets": 152_987.0,      # Total current assets
    "current_liab": 176_392.0,        # Total current liabilities
    "total_assets": 364_980.0,        # Total assets
    "total_liabilities": 308_030.0,   # Total liabilities
    "total_equity": 56_950.0,         # Total shareholders' equity
    "retained_earnings": -19_154.0,   # Accumulated deficit
    "payables": 68_960.0,             # Accounts payable
    # Term debt (current 10,912 + commercial paper 9,967 + non-current 85,750)
    "total_debt": 106_629.0,
    # Consolidated Statements of Cash Flows
    "ocf": 118_254.0,                 # Cash generated by operating activities
    "capex": -9_447.0,                # Payments for acquisition of PP&E
    "d_and_a": 11_445.0,              # Depreciation and amortization
    # Market data is not in the filing; a round figure is used so the expected
    # valuation numbers below are reproducible by hand.
    "market_cap": 3_400_000.0,
}

AAPL_FY2023 = {
    "revenue": 383_285.0,
    "cogs": 214_137.0,
    "gross_profit": 169_148.0,
    "operating_income": 114_301.0,
    "net_income": 96_995.0,
    "total_assets": 352_583.0,
    "total_equity": 62_146.0,
    "cash": 29_965.0,
    "total_debt": 111_088.0,
    "ocf": 110_543.0,
    "capex": -10_959.0,
}


@pytest.fixture
def fy24():
    """FY2024 with the derived fields the data layer would have filled in."""
    from src.data.fundamentals import derive

    row = derive(dict(AAPL_FY2024))
    row["market_cap"] = AAPL_FY2024["market_cap"]
    row["enterprise_value"] = (
        row["market_cap"] + row["total_debt"] - row["cash"]
    )
    return row


@pytest.fixture
def fy23():
    from src.data.fundamentals import derive

    return derive(dict(AAPL_FY2023))


# ------------------------------------------------------------------------ primitives


class TestPrimitives:
    def test_safe_div_normal(self):
        assert r.safe_div(10.0, 4.0) == 2.5

    @pytest.mark.parametrize(
        "num,den", [(None, 4.0), (10.0, None), (10.0, 0.0), (None, None)]
    )
    def test_safe_div_returns_none_never_zero_or_inf(self, num, den):
        assert r.safe_div(num, den) is None

    def test_safe_div_can_reject_negative_denominators(self):
        assert r.safe_div(10.0, -5.0) == -2.0
        assert r.safe_div(10.0, -5.0, allow_negative_denom=False) is None

    def test_average_of_balances(self):
        assert r.average(100.0, 200.0) == 150.0
        assert r.average(100.0, None) == 100.0
        assert r.average(None, 200.0) == 200.0
        assert r.average(None, None) is None

    def test_pct_change_refuses_a_non_positive_base(self):
        assert r.pct_change(110.0, 100.0) == pytest.approx(0.10)
        assert r.pct_change(5.0, -10.0) is None
        assert r.pct_change(5.0, 0.0) is None

    def test_cagr(self):
        # 100 -> 121 over two years is exactly 10% a year.
        assert r.cagr(121.0, 100.0, 2.0) == pytest.approx(0.10, rel=1e-9)

    def test_cagr_refuses_negative_or_zero_endpoints(self):
        assert r.cagr(121.0, -100.0, 2.0) is None
        assert r.cagr(-121.0, 100.0, 2.0) is None
        assert r.cagr(121.0, 0.0, 2.0) is None
        assert r.cagr(121.0, 100.0, 0.0) is None


# --------------------------------------------------------------------- profitability


class TestProfitability:
    def test_gross_margin(self, fy24):
        # 180,683 / 391,035 = 0.462063
        assert r.gross_margin(fy24) == pytest.approx(0.462063, abs=1e-6)

    def test_operating_margin(self, fy24):
        # 123,216 / 391,035 = 0.315103
        assert r.operating_margin(fy24) == pytest.approx(0.315103, abs=1e-6)

    def test_net_margin(self, fy24):
        # 93,736 / 391,035 = 0.239712
        assert r.net_margin(fy24) == pytest.approx(0.239712, abs=1e-6)

    def test_ebitda_margin(self, fy24):
        # EBITDA falls back to EBIT + D&A = 123,216 + 11,445 = 134,661
        # 134,661 / 391,035 = 0.344370
        assert fy24["ebitda"] == 134_661.0
        assert r.ebitda_margin(fy24) == pytest.approx(0.344370, abs=1e-6)

    def test_fcf_margin(self, fy24):
        # FCF = 118,254 - |−9,447| = 108,807 ; / 391,035 = 0.278254
        assert fy24["fcf"] == 108_807.0
        assert r.fcf_margin(fy24) == pytest.approx(0.278254, abs=1e-6)

    def test_roe_uses_average_equity_not_ending_equity(self, fy24, fy23):
        # avg equity = (56,950 + 62,146) / 2 = 59,548
        # 93,736 / 59,548 = 1.574125
        assert r.roe(fy24, fy23) == pytest.approx(1.574125, abs=1e-6)
        # Ending-equity ROE would be 1.6460 — materially different, so the test bites.
        assert r.roe(fy24, fy23) != pytest.approx(93_736.0 / 56_950.0, abs=1e-3)

    def test_roa(self, fy24, fy23):
        # avg assets = (364,980 + 352,583) / 2 = 358,781.5
        # 93,736 / 358,781.5 = 0.261262
        assert r.roa(fy24, fy23) == pytest.approx(0.261262, abs=1e-6)

    def test_invested_capital(self, fy24):
        # 106,629 + 56,950 - 29,943 = 133,636
        assert r.invested_capital(fy24) == 133_636.0

    def test_roic(self, fy24, fy23):
        # NOPAT = 123,216 x (1 - 29,749/123,485) = 123,216 x 0.7590883 = 93,531.81
        # IC FY24 = 133,636 ; IC FY23 = 111,088 + 62,146 - 29,965 = 143,269
        # avg IC = 138,452.5 ; 93,531.81 / 138,452.5 = 0.675552
        assert fy24["nopat"] == pytest.approx(93_531.81, abs=0.5)
        assert r.roic(fy24, fy23) == pytest.approx(0.675552, abs=1e-5)

    def test_asset_turnover(self, fy24, fy23):
        # 391,035 / 358,781.5 = 1.089897
        assert r.asset_turnover(fy24, fy23) == pytest.approx(1.089897, abs=1e-6)

    def test_equity_multiplier(self, fy24, fy23):
        # 358,781.5 / 59,548 = 6.025081
        assert r.equity_multiplier(fy24, fy23) == pytest.approx(6.025081, abs=1e-6)

    def test_dupont_identity_reconciles(self, fy24, fy23):
        d = r.dupont(fy24, fy23)
        # 0.239712 x 1.089897 x 6.024762 = 1.574109, which is ROE computed directly.
        assert d["product"] == pytest.approx(d["roe_direct"], rel=1e-9)
        assert d["reconciles"] is True


# --------------------------------------------------------------- liquidity, solvency


class TestLiquidityAndSolvency:
    def test_current_ratio(self, fy24):
        # 152,987 / 176,392 = 0.867313  (Apple runs a working-capital deficit)
        assert r.current_ratio(fy24) == pytest.approx(0.867313, abs=1e-6)

    def test_quick_ratio_excludes_inventory(self, fy24):
        # (152,987 - 7,286) / 176,392 = 0.826007
        assert r.quick_ratio(fy24) == pytest.approx(0.826007, abs=1e-6)

    def test_cash_ratio(self, fy24):
        # 29,943 / 176,392 = 0.169752
        assert r.cash_ratio(fy24) == pytest.approx(0.169752, abs=1e-6)

    def test_debt_to_equity(self, fy24):
        # 106,629 / 56,950 = 1.872327
        assert r.debt_to_equity(fy24) == pytest.approx(1.872327, abs=1e-6)

    def test_net_debt(self, fy24):
        # 106,629 - 29,943 = 76,686
        assert r.net_debt(fy24) == 76_686.0

    def test_net_debt_to_ebitda(self, fy24):
        # 76,686 / 134,661 = 0.569474
        assert r.net_debt_to_ebitda(fy24) == pytest.approx(0.569474, abs=1e-6)

    def test_interest_coverage(self, fy24):
        row = dict(fy24, interest_expense=-3_750.0)
        # 123,216 / 3,750 = 32.8576  (absolute value of interest expense)
        assert r.interest_coverage(row) == pytest.approx(32.8576, abs=1e-4)

    def test_fcf_to_debt(self, fy24):
        # 108,807 / 106,629 = 1.020426
        assert r.fcf_to_debt(fy24) == pytest.approx(1.020426, abs=1e-6)

    def test_dso(self, fy24):
        # 33,410 / 391,035 x 365 = 31.1856 days
        assert r.dso(fy24) == pytest.approx(31.1856, abs=1e-4)

    def test_dio(self, fy24):
        # 7,286 / 210,352 x 365 = 12.6426 days
        assert r.dio(fy24) == pytest.approx(12.6426, abs=1e-4)

    def test_dpo(self, fy24):
        # 68,960 / 210,352 x 365 = 119.6585 days
        assert r.dpo(fy24) == pytest.approx(119.6585, abs=1e-4)

    def test_cash_conversion_cycle(self, fy24):
        # 31.1856 + 12.6426 - 119.6585 = -75.8303 days: Apple is financed by suppliers.
        assert r.cash_conversion_cycle(fy24) == pytest.approx(-75.8303, abs=1e-3)

    def test_altman_z(self, fy24):
        # 1.2(-23,405/364,980) = -0.076952
        # 1.4(-19,154/364,980) = -0.073472
        # 3.3(123,216/364,980) =  1.114067
        # 0.6(3,400,000/308,030) = 6.622731
        # 1.0(391,035/364,980) =  1.071387
        #                        ---------
        #                         8.657764
        assert r.altman_z(fy24) == pytest.approx(8.657764, abs=1e-5)

    def test_altman_bands(self):
        assert r.altman_band(3.5) == "safe"
        assert r.altman_band(2.5) == "grey"
        assert r.altman_band(1.0) == "distress"
        assert r.altman_band(2.99) == "grey"     # boundary is exclusive above
        assert r.altman_band(1.81) == "grey"     # boundary is inclusive below
        assert r.altman_band(None) is None


# -------------------------------------------------------------------------- valuation


class TestValuation:
    def test_enterprise_value(self, fy24):
        # 3,400,000 + 106,629 - 29,943 = 3,476,686
        assert fy24["enterprise_value"] == 3_476_686.0

    def test_pe(self, fy24):
        # 3,400,000 / 93,736 = 36.27
        assert r.pe_ratio(fy24) == pytest.approx(36.2727, abs=1e-3)

    def test_ev_ebitda(self, fy24):
        # 3,476,686 / 134,661 = 25.8182
        assert r.ev_ebitda(fy24) == pytest.approx(25.8182, abs=1e-3)

    def test_ev_sales(self, fy24):
        # 3,476,686 / 391,035 = 8.8910
        assert r.ev_sales(fy24) == pytest.approx(8.8910, abs=1e-3)

    def test_price_to_book(self, fy24):
        # 3,400,000 / 56,950 = 59.7015
        assert r.price_to_book(fy24) == pytest.approx(59.7015, abs=1e-3)

    def test_fcf_yield(self, fy24):
        # 108,807 / 3,400,000 = 0.032002
        assert r.fcf_yield(fy24) == pytest.approx(0.032002, abs=1e-6)

    def test_peg(self, fy24):
        # P/E 36.2727 over 12% growth = 3.0227
        assert r.peg_ratio(fy24, 0.12) == pytest.approx(3.0227, abs=1e-3)

    def test_peg_undefined_without_positive_growth(self, fy24):
        assert r.peg_ratio(fy24, -0.05) is None
        assert r.peg_ratio(fy24, None) is None


# ----------------------------------------------------------------------------- trends


class TestTrends:
    # Apple net sales, newest first, from the FY2024 and FY2022 filings.
    REVENUE = [
        ("FY2024", 391_035.0),
        ("FY2023", 383_285.0),
        ("FY2022", 394_328.0),
        ("FY2021", 365_817.0),
        ("FY2020", 274_515.0),
    ]

    def test_yoy(self):
        # (391,035 - 383,285) / 383,285 = 0.020220
        assert t.yoy(self.REVENUE) == pytest.approx(0.020220, abs=1e-6)

    def test_yoy_prior_period(self):
        # (383,285 - 394,328) / 394,328 = -0.028005
        assert t.yoy(self.REVENUE, offset=1) == pytest.approx(-0.028005, abs=1e-6)

    def test_growth_acceleration(self):
        # 0.020220 - (-0.028005) = 0.048225
        assert t.growth_acceleration(self.REVENUE) == pytest.approx(0.048225, abs=1e-6)

    def test_cagr_3y(self):
        # (391,035 / 365,817) ^ (1/3) - 1 = 0.022470
        assert t.cagr_over(self.REVENUE, 3) == pytest.approx(0.022470, abs=1e-6)

    def test_cagr_4y(self):
        # (391,035 / 274,515) ^ (1/4) - 1 = 0.092477
        assert t.cagr_over(self.REVENUE, 4) == pytest.approx(0.092477, abs=1e-6)

    def test_cagr_needs_enough_history(self):
        assert t.cagr_over(self.REVENUE[:2], 3) is None

    def test_incremental_operating_margin(self):
        profit = [("FY2024", 123_216.0), ("FY2023", 114_301.0)]
        # (123,216 - 114,301) / (391,035 - 383,285) = 8,915 / 7,750 = 1.150323
        assert t.incremental_margin(self.REVENUE, profit) == pytest.approx(1.150323, abs=1e-6)

    def test_incremental_margin_undefined_when_revenue_shrank(self):
        rev = [("FY2024", 380_000.0), ("FY2023", 391_035.0)]
        profit = [("FY2024", 100_000.0), ("FY2023", 123_216.0)]
        assert t.incremental_margin(rev, profit) is None

    def test_reinvestment_rate(self, fy24):
        # |−9,447| / 118,254 = 0.079887
        assert t.reinvestment_rate(fy24) == pytest.approx(0.079887, abs=1e-6)

    def test_rule_of_40(self):
        # 20% growth + 25% FCF margin = 45
        assert t.rule_of_40(0.20, 0.25) == pytest.approx(45.0)
        assert t.rule_of_40(None, 0.25) is None

    def test_derive_eps_prefers_the_reported_figure(self, fy24):
        assert t.derive_eps(fy24) == 6.08

    def test_derive_eps_falls_back_to_the_quotient(self):
        # 93,736 / 15,408.095 = 6.0835, close to the reported 6.08
        row = {"net_income": 93_736.0, "shares_diluted": 15_408.095}
        assert t.derive_eps(row) == pytest.approx(6.0835, abs=1e-3)

    def test_median(self):
        assert t.median([3.0, 1.0, 2.0]) == 2.0
        assert t.median([4.0, 1.0, 3.0, 2.0]) == 2.5
        assert t.median([None, None]) is None


class TestPercentileRank:
    def test_ranks_within_peers(self):
        # 3 of 4 peers sit below 20 -> 0.75
        assert t.percentile_rank(20.0, [5.0, 10.0, 15.0, 25.0]) == pytest.approx(0.75)

    def test_direction_inverts_for_lower_is_better(self):
        assert t.percentile_rank(20.0, [5.0, 10.0, 15.0, 25.0], higher_is_better=False) == pytest.approx(0.25)

    def test_requires_three_valid_peers(self):
        assert t.percentile_rank(20.0, [5.0, 10.0]) is None
        assert t.percentile_rank(20.0, [5.0, 10.0, None]) is None
        assert t.percentile_rank(20.0, [5.0, 10.0, 15.0]) is not None

    def test_ties_place_at_the_midpoint(self):
        assert t.percentile_rank(10.0, [10.0, 10.0, 10.0]) == pytest.approx(0.5)

    def test_none_value_ranks_nowhere(self):
        assert t.percentile_rank(None, [1.0, 2.0, 3.0]) is None
